steps:
  # Step 1: Restore cache from previous builds
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'restore-cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d gs://${PROJECT_ID}_cloudbuild_cache/pip-cache .cache/pip || echo "No cache found, starting fresh"

  # Step 2: Install production dependencies with caching
  - name: 'python:3.12'
    id: 'install-deps'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', '--user', '--cache-dir', '.cache/pip']
    waitFor: ['restore-cache']

  # Step 3: Install test dependencies with caching
  - name: 'python:3.12'
    id: 'install-test-deps'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements-test.txt', '--user', '--cache-dir', '.cache/pip']
    waitFor: ['install-deps']

  # Step 4: Run tests with coverage reporting
  - name: 'python:3.12'
    id: 'run-tests'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'tests/', '--verbose', '--cov=.', '--cov-report=term-missing', '--cov-report=xml']
    env:
      - 'USE_FIRESTORE=false'
    waitFor: ['install-test-deps']

  # Step 5: Save cache for next build (optimization)
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'save-cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil -m rsync -r -d .cache/pip gs://${PROJECT_ID}_cloudbuild_cache/pip-cache || echo "Cache save failed, continuing with deployment"
    waitFor: ['run-tests']

  # Step 6: Deploy to App Engine (automatic on main branch)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args: ['app', 'deploy', '--quiet', '--version=${SHORT_SHA}']
    timeout: '1600s'
    waitFor: ['run-tests']

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '2000s'
