steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/adviser-allocation/adviser-allocation:${SHORT_SHA}'
      - '-t'
      - 'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/adviser-allocation/adviser-allocation:latest'
      - '.'

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - 'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/adviser-allocation/adviser-allocation'
    waitFor: ['build']

  # Step 3: Run tests inside container
  - name: 'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/adviser-allocation/adviser-allocation:${SHORT_SHA}'
    id: 'test'
    entrypoint: 'python'
    args:
      - '-m'
      - 'pytest'
      - '--verbose'
      - '--cov=adviser_allocation'
      - '--cov-report=term-missing'
      - '--timeout=60'
    env:
      - 'USE_FIRESTORE=false'
      - 'PYTHONPATH=src'
    waitFor: ['push']

  # Step 4: Deploy to Cloud Run (canary, no traffic)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args:
      - 'run'
      - 'deploy'
      - 'adviser-allocation'
      - '--image=australia-southeast1-docker.pkg.dev/${PROJECT_ID}/adviser-allocation/adviser-allocation:${SHORT_SHA}'
      - '--region=australia-southeast1'
      - '--platform=managed'
      - '--tag=canary'
      - '--no-traffic'
    timeout: '600s'
    waitFor: ['test']

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

images:
  - 'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/adviser-allocation/adviser-allocation:${SHORT_SHA}'
  - 'australia-southeast1-docker.pkg.dev/${PROJECT_ID}/adviser-allocation/adviser-allocation:latest'

timeout: '1800s'
